In [4]:
# Підтримка векторних машин (SVM) з пошуком гіперпараметрів (GridSearchCV)

import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# 1. Завантажуємо дані про вино
wine_data = load_wine()
X = pd.DataFrame(wine_data['data'], columns=wine_data['feature_names'])  # ознаки
y = wine_data['target']  # мітки класів

# 2. Розділяємо дані на навчальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=101
)

# 3. Стандартизуємо ознаки
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # підгонка та трансформація навчальних даних
X_test_scaled = scaler.transform(X_test)        # трансформація тестових даних

# 4. Створюємо модель SVM з початковими параметрами
svm_model = SVC(C=1.0, gamma=1.0, kernel='rbf')
svm_model.fit(X_train_scaled, y_train)  # навчання моделі

# 5. Прогнозування та оцінка моделі
y_pred = svm_model.predict(X_test_scaled)
print("Матриця неточностей:\n", confusion_matrix(y_test, y_pred))
print("\nЗвіт класифікації:\n", classification_report(y_test, y_pred))

# 6. Пошук оптимальних гіперпараметрів за допомогою GridSearchCV
param_grid = {
    'C': [0.1, 1, 10, 100, 1000],           # параметр регуляризації
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001], # параметр ядра RBF
    'kernel': ['rbf']                        # використання RBF ядра
}

grid = GridSearchCV(SVC(), param_grid, refit=True)
grid.fit(X_train_scaled, y_train)  # навчання моделі з пошуком найкращих параметрів

# 7. Найкращі параметри та прогнозування з оптимізованою моделлю
print("Найкращі параметри:", grid.best_params_)
grid_pred = grid.predict(X_test_scaled)
print("\nМатриця неточностей (GridSearch):\n", confusion_matrix(y_test, grid_pred))
print("\nЗвіт класифікації (GridSearch):\n", classification_report(y_test, grid_pred))


Матриця неточностей:
 [[ 8 11  0]
 [ 0 22  0]
 [ 0 10  3]]

Звіт класифікації:
               precision    recall  f1-score   support

           0       1.00      0.42      0.59        19
           1       0.51      1.00      0.68        22
           2       1.00      0.23      0.38        13

    accuracy                           0.61        54
   macro avg       0.84      0.55      0.55        54
weighted avg       0.80      0.61      0.57        54

Найкращі параметри: {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

Матриця неточностей (GridSearch):
 [[19  0  0]
 [ 0 20  2]
 [ 0  0 13]]

Звіт класифікації (GridSearch):
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.91      0.95        22
           2       0.87      1.00      0.93        13

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96 